apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::864897371056:role/eksctl-flask-ap-nodegroup-ng-cf1c-NodeInstanceRole-1FZK16UN9ONUV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::864897371056:role/FlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-11T02:09:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1569"
  uid: a794fd44-f39d-49bb-8434-b2c4ad9cc02a
