apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::169468262340:role/eksctl-flask-k8-nodegroup-ng-1e73-NodeInstanceRole-1EJFAXHGBQ9GH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::169468262340:role/FlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-14T02:04:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1622"
  uid: 55467afb-0cc7-4eb0-8ac8-68c22dae8466
